# THE ZEN C DOCUMENTATION CONFIG
base_url = "https://docs.zenc-lang.org"
title = "Zen C Documentation"
description = "Official Grimoire for the Zen C Systems Language."
default_language = "en"

# THEME SETTINGS
compile_sass = false
highlight_code = true
highlight_theme = "css" # We will use our own CSS variables for colors

[extra]
version = "v0.4.3"
github_url = "https://github.com/zenc-lang/zenc"

[markdown]
render_emoji = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_with_code_block_copy_button = true

[search]
build_search_index = true
